# DAY 9- NUMPY

# PS1

In [3]:
import numpy as np

a=np.random.random((3,3,3))
print(a)

[[[0.35861099 0.68616024 0.94332989]
  [0.99968655 0.93926212 0.97656749]
  [0.39630693 0.17401538 0.33769451]]

 [[0.06851447 0.74030671 0.9168986 ]
  [0.33805981 0.34022913 0.69832314]
  [0.46005021 0.6266915  0.13630784]]

 [[0.60184412 0.0292622  0.28372909]
  [0.64975794 0.55002825 0.16248368]
  [0.35188543 0.16438684 0.93049658]]]


# PS2

In [4]:
import numpy as np

lst=[[0,0,0,0,0],[1,0,0,0,0],[2,2,0,0,0],[3,3,3,0,0],[4,4,4,4,0]]

a2=np.array(lst)
print(a2)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [2 2 0 0 0]
 [3 3 3 0 0]
 [4 4 4 4 0]]


# PS3

In [32]:
import numpy as np
lst=['a','b','c','d','e','f','g','h']
lst1=['1','2','3','4','5','6','7','8']
lst2=[]
lst2=[[]for i in range(8)]
for i in range(len(lst)):
    
    for j in range(len(lst)):
        lst2[i].append(lst[i]+lst1[j])
    
print(lst2)
a3=np.array(lst2)
print(a3)

[['a1', 'a2', 'a3', 'a4', 'a5', 'a6', 'a7', 'a8'], ['b1', 'b2', 'b3', 'b4', 'b5', 'b6', 'b7', 'b8'], ['c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8'], ['d1', 'd2', 'd3', 'd4', 'd5', 'd6', 'd7', 'd8'], ['e1', 'e2', 'e3', 'e4', 'e5', 'e6', 'e7', 'e8'], ['f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8'], ['g1', 'g2', 'g3', 'g4', 'g5', 'g6', 'g7', 'g8'], ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'h7', 'h8']]
[['a1' 'a2' 'a3' 'a4' 'a5' 'a6' 'a7' 'a8']
 ['b1' 'b2' 'b3' 'b4' 'b5' 'b6' 'b7' 'b8']
 ['c1' 'c2' 'c3' 'c4' 'c5' 'c6' 'c7' 'c8']
 ['d1' 'd2' 'd3' 'd4' 'd5' 'd6' 'd7' 'd8']
 ['e1' 'e2' 'e3' 'e4' 'e5' 'e6' 'e7' 'e8']
 ['f1' 'f2' 'f3' 'f4' 'f5' 'f6' 'f7' 'f8']
 ['g1' 'g2' 'g3' 'g4' 'g5' 'g6' 'g7' 'g8']
 ['h1' 'h2' 'h3' 'h4' 'h5' 'h6' 'h7' 'h8']]


# PS4

In [51]:
import numpy as np

lst4=[[1,2,2,0,0],[2,1,2,1,0],[1,2,0,2,1],[1,1,1,1,2],[2,2,2,1,0]]
a4=np.array(lst4)
print(a4)
det=np.linalg.det(a4)
print('\n',det)
print('\nNormalized matrix is\n')
print(a4/det)

[[1 2 2 0 0]
 [2 1 2 1 0]
 [1 2 0 2 1]
 [1 1 1 1 2]
 [2 2 2 1 0]]

 2.9999999999999996

Normalized matrix is

[[0.33333333 0.66666667 0.66666667 0.         0.        ]
 [0.66666667 0.33333333 0.66666667 0.33333333 0.        ]
 [0.33333333 0.66666667 0.         0.66666667 0.33333333]
 [0.33333333 0.33333333 0.33333333 0.33333333 0.66666667]
 [0.66666667 0.66666667 0.66666667 0.33333333 0.        ]]


# PS5

In [56]:
lst51=[[1,2,2,0,0],[2,1,2,1,0]]
lst52=[[1,2,0,2,1],[1,1,1,1,2]]
a51=np.array(lst51)
a52=np.array(lst52)


a5=a51-a52
for i in range(len(a5)):
    for j in range(len(a5)):
        if a5[i][j]==0:
            print('same value ',a51[i][j],' at ',i,',',j)


same value  1  at  0 , 0
same value  2  at  0 , 1
same value  1  at  1 , 1


# PS6

In [129]:
import numpy as np
  

today = np.datetime64('today', 'D')
print( today)
  
yesterday = np.datetime64('today', 'D')- np.timedelta64(1, 'D')
  
print( yesterday)

tomorrow = np.datetime64('today', 'D')+ np.timedelta64(1, 'D')
  
print( tomorrow)

2023-09-22
2023-09-21
2023-09-23


# PS7

In [72]:
a71=np.random.random((3,3))
a72=np.random.random((3,3))
print(a71)
print(a72)
flag=0
for i in range(len(a71)):
    for j in range(len(a71)):
        if a71[i][j]!=a72[i][j]:
            flag=1
            break
if flag==1:
    print('different array')
else:
    print('same array')

[[0.64656057 0.50170177 0.72634164]
 [0.97686332 0.80558697 0.40329392]
 [0.07257615 0.99407068 0.90611119]]
[[0.61881416 0.46081222 0.94769346]
 [0.28566271 0.08441422 0.65400119]
 [0.35308463 0.34178265 0.63348865]]
different array


# PS8

In [ ]:
import numpy as np

a=np.random.randint(0,10,10)

print(a)

b=np.max(a)

print(b)

for i in range(len(a)):
    if a[i]==b:
        a[i]=0
        
print(a)

# PS9

In [107]:
lst4=[[1,2,2,0,0],[2,1,2,0,0],[0,2,0,2,1],[1,1,1,1,1],[2,2,0,1,0]]
a4=np.array(lst4)
print('Printing all elements of the array')
print()
print(a4)

Printing all elements of the array

[[1 2 2 0 0]
 [2 1 2 0 0]
 [0 2 0 2 1]
 [1 1 1 1 1]
 [2 2 0 1 0]]


# PS10

In [106]:
lst4=[[1,2,2,0,0],[2,1,2,0,0],[0,2,0,2,1],[1,1,1,1,1],[2,2,0,1,0]]
a4=np.array(lst4)
for i in range(len(a4)):
    a=np.average(a4[i])
    for j in range(len(a4[i])):
        a4[i][j]-=a
        
print(a4)
        

[[ 0  1  1 -1 -1]
 [ 1  0  1 -1 -1]
 [-1  1 -1  1  0]
 [ 0  0  0  0  0]
 [ 1  1 -1  0 -1]]


# PS11

In [137]:
import numpy as np
lst=[1,2,2,0,0]

a=np.array(lst)
print(a)
a2=np.random.randint(0,5,2)
print(a2)
for i in range(len(a)):
    if i in a2:
        a[i]+=1
        
print(a)

[1 2 2 0 0]
[1 0]
[2 3 2 0 0]


# PS12

In [142]:
import numpy as np
x=np.array([[1,2,3,4],[3,4,5,6]])
v=np.array([9,10,11,12])
print(np.diag(x.dot(v)))

[[110   0]
 [  0 194]]


# PS13

In [79]:
import numpy as np
x=np.random.randint(0,10,50)
di={}
for i in range(len(x)):
    if x[i] not in di:
        di[x[i]]=1
    else:
        di[x[i]]+=1
print(x)
print(di)
ma=max(di.values())
for k in di:
    v=di[k]
    if v==ma:
        print(k,':',v)



[7 1 8 6 5 8 9 9 8 3 4 4 8 8 3 0 9 0 6 4 5 9 7 3 0 0 0 2 9 3 5 5 9 6 9 2 7
 1 3 7 8 2 8 1 8 7 4 3 0 0]
{7: 5, 1: 3, 8: 8, 6: 3, 5: 4, 9: 7, 3: 6, 4: 4, 0: 7, 2: 3}
8 : 8


# PS14

In [91]:
import numpy as np
a=np.random.randint(0,10,10)
print(a)
n=int(input('Enter number of largest number(n) :'))
a.sort()
print(a)
print(a[-n:])

[5 0 0 1 8 8 7 2 4 9]
Enter number of largest number(n) :4
[0 0 1 2 4 5 7 8 8 9]
[7 8 8 9]


# PS15

In [108]:
import numpy as np
arr = np.array([("om", 88.5, 90),
                 ("tom", 87, 99),
             ("son", 85.5, 91)])

print(arr)
print("\nRecord array;")
result = np.core.records.fromarrays(arr.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print(result)

[['om' '88.5' '90']
 ['tom' '87' '99']
 ['son' '85.5' '91']]

Record array;
[(b'om', 88.5, 90) (b'tom', 87. , 99) (b'son', 85.5, 91)]


# PS16

In [85]:
a=np.array([[23,34,121],[23,22,67],[686,343,563]])
print(a)
n1=int(input('Enter the rows to swap(1,2,3): '))
n2=int(input())

for i in range(3):
    a[n1-1][i],a[n2-1][i]=a[n2-1][i],a[n1-1][i]
print(a)


[[ 23  34 121]
 [ 23  22  67]
 [686 343 563]]
Enter the rows to swap(1,2,3): 1
2
[[ 23  22  67]
 [ 23  34 121]
 [686 343 563]]


# PS17

In [82]:
x=np.array([[23,34,121],[23,22,67],[686,343,563]])
xx=x.reshape((x.shape[0],x.shape[1],1))
print(xx)

[[[ 23]
  [ 34]
  [121]]

 [[ 23]
  [ 22]
  [ 67]]

 [[686]
  [343]
  [563]]]
